### ISSUE TITLE
Loading WMS into QGIS not working

### ISSUE THREAD

**Issue by bellerophons-pegasus** [acdh-oeaw/ACDHhackathonODDVie#1]
I'm not sure if this is just me or if it is a general issue. I tried loading the WMS layer BOMBENSCHADENOGD  into QGIS (3.4), which only results in a white rectangle.
WMS layers from other sources load fine.

**Comment by zozlak** [comment]
The WMS service providing the map has some limitations:

* it doesn't properly return map's bounding box, so "zoom to the layer" QGIS feature doesn't work
* it doesn't return any data if the zoom level is to small or too big

Workaround:

* add another layer to the map (e.g. open street maps or google) and move your view to the Vienna
* zoom in/out so Vienna covers more or less whole screen
* add the BOMBENSCHADENOGD layer (and maybe try to zoom in a little if it's still not displayed)

**Comment by bellerophons-pegasus** [comment]
Yes, that works for me.
